### ISSUE TITLE
BUGS!

### ISSUE THREAD

**Issue by dis446** [dis446/Fallout-Shelter-Text-Based#1]
BUGS!!!. BUGS EVERYWHERE!!!
MULTIPLE SYSTEMS NOT WORKING!!!

**Comment by The-9880** [comment]
Hit the panic button - it's the only thing to do.

**Comment by dis446** [comment]
THAT SYSTEM DOESN'T WORK EITHER.

**Comment by The-9880** [comment]
gg wp rekt

**Comment by dis446** [comment]
Game Framework done.  Now comes the most annoying part. Squashing bugs. Starting with the rand_item function. Syntax error occurs, But I don't understand it.
