### ISSUE TITLE
User Documentation

### ISSUE THREAD

**Issue by dis446** [dis446/Fallout-Shelter-Text-Based#10]
In the main game loop, need to print out the instructions for the user. There's already some of it there, but it's incomplete and outdated.

**Comment by sgtlaggy** [comment]
Working on this right now

**Comment by dis446** [comment]
Thanks. What I mean is that at the beginning of the game, user instructions should be printed, detailing what commands they can enter. There's already some is it there, but its updated. Just leave it to me actually.

**Comment by dis446** [comment]
The print_help() function is great! Just need to update it once in a  while, as new things are added to the game.
