### ISSUE TITLE
Change the implementation of assigned rooms 

### ISSUE THREAD

**Issue by kungtotte** [dis446/Fallout-Shelter-Text-Based#24]
It's cumbersome and error prone to have assigned rooms implemented as a string, it's better to use a dict (or a set, to enforce unique values), and pass around person objects.

E.g: 

```
if person in room.assigned:
    # person object found in the dict

for person in room.assigned:
    # do efficiency calcs here, etc. Easily allows 
    # per-person boosts like:
    # boost += person.intelligence
```

**Comment by sgtlaggy** [comment]
Why should it be a dict, rather than a list?

**Comment by kungtotte** [comment]
It should actually be a list. The dict thing was just because I was stuck thinking about the way people are currently handled (with string references to their names).

**Comment by mikevb1** [comment]
See [this blog post](http://opensourcehacker.com/2012/05/13/never-use-hard-tabs/), [this SO post](http://stackoverflow.com/questions/9446109/soft-tabs-or-hard-tabs) or [this emacs wiki article](https://www.emacswiki.org/emacs/TabsAreEvil).

**Comment by dis446** [comment]
Currently, rooms keep track of which inhabitants are in them with a weird string of binary numbers. I.e. 100010 means that the 1st and 5th people are assigned to the room. Transitioning from a list to a dictionary ( for the people) has broken this system.
We need a new way for rooms to know who's assigned to them.
I would recommend having the room.assigned variable set to a list of the names of the people assigned there, as mentioned before. This can be easily cross-referenced with the people dictionary.
