### ISSUE TITLE
Add string representation to classes

### ISSUE THREAD

**Issue by kungtotte** [dis446/Fallout-Shelter-Text-Based#27]
Instead of constructing a string with Firstname Lastname etc. when referring to or printing a Person (or other object), we should implement the `__str__` special method to do it automatically.

E.g: 

``` python

class Human:
    def __str__(self):
        return "{} {}".format(self.firstname, self.surname)

p = Human("Joe", "Smith")
print(p) # automatically calls p.__str__
if str(p) == "Joe Smith":
    # same thing here, str() automatically calls p.__str()__
```

**Comment by dis446** [comment]
That's a much simpler way to do it. Thanks.

**Comment by sgtlaggy** [comment]
Since you mentioned str.format(), should we move to formatting from string concatenation? Concatenation just looks a bit messy with strings and variables intertwined.

**Comment by kungtotte** [comment]
`format` is better than concatenation.

It also allows you to save a format string and reuse it easily.

Example:

``` python
warning = "Warning! {} is almost dying from {}."

if hunger >  80:
    print(warning.format(person, 'hunger')

if thirst > 80:
    print(warning.format(person, 'thirst')
```

**Comment by sgtlaggy** [comment]
Would anyone else like to work on this issue?

**Comment by dis446** [comment]
I implemented the **str** method.  Printing out the names using this seems simple enough. Just need to work out how to use it to reference people.

**Comment by sgtlaggy** [comment]
What do you mean reference people? The `__str__` method is only used used when you call the Human object in a print or str call, or call the `__str__` method directly.

**Comment by dis446** [comment]
Forget it. Now that I've thought about it, I wouldn't work. The current system (calling get_person_index(first_name,last_name)) works.

**Comment by sgtlaggy** [comment]
Maybe use a dict for people, full name (`str(human_obj)`) as the key, object as the value? Plus we really should be using `str(human_obj)` as the argument instead of first_name and surname.

**Comment by dis446** [comment]
That would work. But I don't feel like implementing a new solution when the current one already works (weirdly, but it works)

**Comment by kungtotte** [comment]
We might as well just stop working on the code all together with that attitude. 

Your post on Reddit specifically asked for help in improving the code, and this is one such improvement. 

The new solution is:
- Less code and more readable
- More Pythonic
- Less error prone
- Makes the language work for us instead of working against it

**Comment by dis446** [comment]
Okay. You've convinced me. Will work on this.

**Comment by sgtlaggy** [comment]
If you're working on an issue, please assign yourself to it so we know someone is working on it.

So general idea of this would be this?
- Turning people[] into people{"Full Name": Human_Obj} 
- Passing "Full Name" to functions instead of first_name and surname (try `" ".join(a.split()[1:3])` if passing from command/"choice" system)?

**Comment by dis446** [comment]
This seems to be done right?
