### ISSUE TITLE
Room System

### ISSUE THREAD

**Issue by dis446** [dis446/Fallout-Shelter-Text-Based#3]
Need a complete reworking of the room class and all the function that work with classes. 
Issues:
Production.
Rushing.
Construction.
Assignment of people.
Just simply storing the rooms!!!
Counting the number of each type of room. E.g. all the living rooms.
Room naming system.

Not looking forward to this...

**Comment by The-9880** [comment]
Proposing an increase in budget so we can rent a corporate HQ and begin hiring freelance programmers. All in favor?

**Comment by The-9880** [comment]
Current projected costs are estimated around 1000 KD.

**Comment by dis446** [comment]
And where would you propose this funding comes from???

**Comment by dis446** [comment]
Okay.
I'm going to completely rework the room system and make it more like the item system.
There can only be one living room in the game and, instead of building new ones, the player will just upgrade the existing ones. This will scale up to a level. Plan to remove room scrapping system.

**Comment by The-9880** [comment]
glhf
