### ISSUE TITLE
Use the built in method title() to format strings.

### ISSUE THREAD

**Issue by kungtotte** [dis446/Fallout-Shelter-Text-Based#34]
Instead of manually making sure that names are capitalized properly we should use the built-in method of doing it, which is `title()`.

Examples:

``` python
"first Last".title() # => "First Last"

"first last".title() # => "First Last"

"FIRST LAST".title() # => "First Last"

"first".title() => "First"
```

The code will be cleaner and more readable.

**Comment by sgtlaggy** [comment]
I didn't even know `str` had a `title` method. Nice find!

**Comment by dis446** [comment]
I think this issue is resolved yeah?

**Comment by sgtlaggy** [comment]
There are still a few places where we have `print_line(variable, " some info here"), which will print out like this:

```
variable
 some info here
```

**Comment by dis446** [comment]
Perhaps we could solve that by making a new function (something like print_one() or something) that does the same thing as print_line(), except it doesn't split it up by lines.
