### ISSUE TITLE
Dispatching bug

### ISSUE THREAD

**Issue by dis446** [dis446/Fallout-Shelter-Text-Based#36]
So I'm sort of out of my element with this whole dispatching actions thing and could use some help. The dispatching isn't working. The system is recognizing whether or not the input is valid or not, but it fails to call the function it needs. Right now, the only thing that works is skipping to the day.

**Comment by sgtlaggy** [comment]
`see inventory` works, `see trader` and `see people` should as well, if they're not empty..

**Comment by dis446** [comment]
Okay yeah sorry it does work.
