### ISSUE TITLE
Print_line

### ISSUE THREAD

**Issue by dis446** [dis446/Fallout-Shelter-Text-Based#39]
See last few comments on #34

**Comment by kungtotte** [comment]
I think it's generally better to have a polymorphic function that can be used for all output. 

When you look at it we have three types of arguments to the output function:
- multiple lines, print line by line
- single line, printing line by line is equivalent to the previous
- variable(s) and a message that should be on one line.

We could try to make the function handle it silently behind the scenes, or we could require callers to construct the output beforehand.

E.g: magic

``` python
def print_lines(*msg):
    if not isinstance(msg[0], str):
        output = ' '.join(msg)
```

Or explicit:

``` python
print_lines(' '.join([var, "foo"])
```

Which is preferable?

**Comment by dis446** [comment]
Magic method seems better. We won't have to manually pass the argument each time we call print_line()

**Comment by kungtotte** [comment]
The only place this new mode of operation takes place in the current code base is when printing resources (food/water/power).

It also accepts any combination of two arguments, so all of the following are equivalent as far as the function is concerned:

``` python
print_line(var, "string")
print_line("string", var)
print_line(var1, var2)
print_line("string 1", "string 2")
```

The upside: I only changed print_line().
The downside: For multiline output you now have to pass three or more arguments, and to get multiline output with two arguments you'd have to call it twice like so:

``` python
print_line("first line")
print_line("second line")
```
