### ISSUE TITLE
Saving to "standard" save locations, cross-platform

### ISSUE THREAD

**Issue by sgtlaggy** [dis446/Fallout-Shelter-Text-Based#40]
Which of [these methods](https://gist.github.com/mikevb1/c385cc13b378fc3a888d) would be preferable? See [pypi/appdirs](https://pypi.python.org/pypi/appdirs/1.4.0) for reference.

**Comment by kungtotte** [comment]
While I think it's always best to keep dependencies down, I like the appdirs approach better. It's cleaner and less error prone, and it is future proof.

We could also have a config/command line argument option to store everything in the application folder to keep it self-contained.

**Comment by sgtlaggy** [comment]
How's the new version of the gist look? Uses "-l" (lowercase L for "local").

**Comment by kungtotte** [comment]
Looks good to me.
