### ISSUE TITLE
Should merge

### ISSUE THREAD

**Issue by dis446** [dis446/Fallout-Shelter-Text-Based#42]
Should we merge the OOP-ify branch into main?
The old system was a lot clunkier and the new OOP has basically solved the globals issue. 
I don't see why we should keep the old system around. It won't properly merge, so I was thinking we should just delete the main branch and replace it with the OOP one.
Thoughts?

**Comment by sgtlaggy** [comment]
Sounds good. Maybe push current `master` to `preoop` just so it's not gone entirely, remove master, then push `OOP-ify` to `master`?
