### ISSUE TITLE
Checking if people exist

### ISSUE THREAD

**Issue by dis446** [dis446/Fallout-Shelter-Text-Based#43]
Hey guys. I've been trying to make the `check_person()` function work. But I can't get the name formatting right. It's checking `if ("Marshall", "Cole")` is in the `game.people` list instead of `"Marshall Cole"`. Could you help me?

**Comment by kungtotte** [comment]
``` python
str = ' '.join(("Marshal", "Cole")) # => "Marshal Cole"

if ' '.join(tuple) in game.people:
    pass
```

**Comment by dis446** [comment]
I tried those methods before, and just tried them again, but they didn't work. I've used `name = name.split()[0].title() + " " + name.split()[1].title()` for now. It works. If you want to, see if you can get the `.join()` method to work.

**Comment by kungtotte** [comment]
As far as I can see you are already passing a string into check_person, so you don't need to do anything inside check_person.

``` python
def check_person(game, name):
    return name.title() in game.people.keys()
```

``` python
if (args[2] == 'to'):
    person_name = ' '.join(args[0:2])
    if check_person(game, name):
        if check_built_room(game, args[3]):
            game = assign_to_room(game, name, args[3])
        else:
             # room stuff
    else:
        # person doesn't exist
```
